### ISSUE TITLE
add Jupyter support

### ISSUE THREAD

**Issue by NChechulin** [wakatime/wakatime-cli#776] opened 2022-10-14 11:09 UTC
**Disclaimer**
I am using an alternative frontend called [wakapi.dev](https://wakapi.dev/). The issue might be on their side, but from my understanding it's not (please, correct me if I'm wrong).

**Is your feature request related to a problem? Please describe.**
Wakapi displays Jupyter as "Unknown language".

**Describe the solution you'd like to see**
Jupyter (`.ipynb`) files be recognized as either Python or Jupyter Notebook language.

**Describe alternatives you've considered**
None, Wakatime suits all my needs.

**Additional context**

WakaTime log entry:
```json
{
    "caller":"pkg/deps/deps.go:65",
    "func":"deps.WithDetection",
    "level":"warning",
    "message":"error parsing language of string \"Jupyter\"",
    "now":"2022-09-23T13:26:40+03:00",
    "version":"v1.55.1"
}
```

**Comment by alanhamlett** [comment] 2023-10-02 20:58
Duplicate of #942

**Closed as completed by alanhamlett** 2023-10-02 20:58 UTC
Labels: feature request, triage
