### ISSUE TITLE
Waiting for wakatime plugins in repl.it IDE

### ISSUE THREAD

**Issue by sudip-mondal-2002** [wakatime/wakatime-cli#458] opened 2021-06-17 07:06 UTC
Eagerly waiting for repl.it plugin
As many institutes does the lab works on repl.it, it should be beneficial to track the coding time.

**Comment by hiyorijl** [comment] 2023-03-30 17:16
also wanting this, since repl.it is getting AI, collaborating with google cloud and everything. it's time.

**Comment by alanhamlett** [comment] 2023-10-02 20:59
Duplicate of #942

**Closed as completed by alanhamlett** 2023-10-02 20:59 UTC
