### ISSUE TITLE
Zotero plugin support

### ISSUE THREAD

**Issue by muety** [wakatime/wakatime-cli#856] opened 2023-03-16 20:21 UTC
Not sure if this is the right place to throw in ideas for new plugins, but I'd love to have a [Zotero](https://zotero.org) one! 

Some useful links:
* [List of Zotero plugins](https://www.zotero.org/support/plugins#developer_tools)
* [Hello World plugin](https://www.zotero.org/support/dev/sample_plugin)

OS, editor and machine are straightforward. The currently opened document's title could map to the entity property. Type could be something like "reading". Branch and language would remain empty. For the project, we could think of having a certain syntax for labels, e.g. if you add `wakatime:Master Thesis` to a document, it would be counted for that project. Or, alternatively, project corresponds to whatever folder a document is placed into.

**Comment by charveey** [comment] 2023-04-22 14:55
I like this idea

**Comment by alanhamlett** [comment] 2023-10-02 20:57
Duplicate of #942

**Closed as completed by alanhamlett** 2023-10-02 20:57 UTC
Labels: feature request, triage
