### ISSUE TITLE
Not working in WSL

### ISSUE THREAD

**Issue by aravindvnair99** [wakatime/wakatime-cli#457] opened 2021-06-17 08:50 UTC
I followed the instructions mentioned at https://wakatime.com/terminal but I get the following error on WSL:

```console
: command not found
bash: /home/<username here>/bash-wakatime.sh: line 12: syntax error near unexpected token `$'{\r''
'ash: /home/<username here>/bash-wakatime.sh: line 12: `pre_prompt_command() {
```

This used to work fine in Git Bash. I recently came over to WSL2 and I am unable to get it to work.

**Comment by gandarez** [comment] 2022-02-15 18:43
Hi, which linux distro have you installed?

**Comment by alanhamlett** [comment] 2022-02-15 19:08
Duplicate of https://github.com/irondoge/bash-wakatime/issues/13.

**Closed as completed by alanhamlett** 2022-02-15 19:08 UTC
Labels: need investigation

**Comment by aravindvnair99** [comment] 2022-02-16 06:46
> Hi, which linux distro have you installed?

@gandarez I have Ubuntu.
