### ISSUE TITLE
Request for support of OneDrive directory

### ISSUE THREAD

**Issue by RalXYZ** [wakatime/wakatime-cli#653] opened 2021-08-28 16:28 UTC
## Problem Description
I use OneDrive to sync my documents. Unfortunately, the Office plugin of Wakatime doesn't support files in OneDrive directory very well.  
If I open a file in OneDrive directory, the Wakatime plugin can no longer send heartbeat to the server. This is the related debug message:  
```
{"now": "2021/08/28 23:55:52 +0800", "version": "13.0.7", "plugin": "word/16.0 word-wakatime/2.1.1", "time": 1630166148.637094, "caller": "wakatime\\main.py", "lineno": 68, "is_write": true, "file": "https://d.docs.live.net/${my_onedrive_id}/Document 1.docx", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}
```

Actually, the path of the opened file is `%UserProfile%\OneDrive\Document 1.docx`.  
However, somehow, Wakatime tries to check the existence of `https://d.docs.live.net/${my_onedrive_id}/Document 1.docx`, which is a web URL. This will obviously lead to the error `File does not exist; ignoring this heartbeat`.

**Comment by alanhamlett** [comment] 2022-06-19 10:47
Duplicate of #489.

**Closed as completed by alanhamlett** 2022-06-19 10:47 UTC
Labels: triage
