### ISSUE TITLE
Notion

### ISSUE THREAD

**Issue by gdpouya** [wakatime/wakatime-cli#1034] opened 2024-02-28 17:07 UTC
please add notion plugin or something we can use on notion or use notion data on wakatime

**Comment by alanhamlett** [comment] 2024-02-29 07:28
Duplicate of https://github.com/wakatime/macos-wakatime/issues/205

Or do you mean for other operating systems besides Mac? Notion doesn't support plugins like WakaTime so we need a native desktop app to track it.

**Closed as not planned by alanhamlett** 2024-02-29 07:28 UTC
Labels: feature request, triage

**Comment by gdpouya** [comment] 2024-03-02 16:55
but on wakatime mac i dont see notion togle button to enable it tacking

**Comment by alanhamlett** [comment] 2024-03-02 19:05
Yes, that issue is still open. We'll update https://github.com/wakatime/macos-wakatime/issues/205 when Notion is supported.
