### ISSUE TITLE
Plugin extension for TeXmacs

### ISSUE THREAD

**Issue by pizhn** [wakatime/wakatime-cli#488] opened 2021-07-04 07:25 UTC
Hi guys I just found this interesting time-recording software. I alreary setup it for most of my working environments. But there is not plugin for [GNU TeXmacs](https://github.com/texmacs/texmacs), it is an amazing WYSIWYG TeX-like editor written in Scheme. I heavily depend on it to write stuff. 
So it's more like a feature request but I know it's rude to request something without contribution :). I'll try to implement one myself when I have spare time (not recent future). I just know a little bit Scheme, therefore I will probably learning by doing.
Just confirming is self-implemented plugin welcomed there? If so, I will find some time to do that, or anybody interested it this thing please feel free to contact me.

**Comment by gandarez** [comment] 2021-07-04 23:53
Yes, all plugins are open source. Contribution is more than welcome.

**Comment by pizhn** [comment] 2021-07-04 23:54
> Yes, all plugins are open source. Contribution is more than welcome.

Thanks for reply Carlos

**Comment by alanhamlett** [comment] 2023-10-02 20:59
Duplicate of #942

**Closed as completed by alanhamlett** 2023-10-02 20:59 UTC
Labels: feature request
